import 'dart:io' show SameSite;

import 'package:PiliPlus/models/common/account_type.dart';
import 'package:PiliPlus/utils/accounts/account.dart';
import 'package:cookie_jar/cookie_jar.dart';

/// Synthetic source state. Stamp generations and Cookie creation timestamps
/// are always generated by the real production Accounts/CookieJar code.
LoginAccount envelopeFixtureAccount(
  String key, {
  Set<AccountType>? purposes,
  String? accessKey = 'synthetic-envelope-access',
  String? refreshToken = 'synthetic-envelope-refresh',
}) => LoginAccount(
  BiliCookieJar.fromJson({
    'DedeUserID': key,
    'bili_jct': 'synthetic-envelope-csrf',
    'SESSDATA': 'synthetic-envelope-session',
  }),
  accessKey,
  refreshToken,
  purposes,
)..activated = true;

/// Seeds the real public jar maps. This is fixture input, not a replica of
/// export, selection, parsing, expiry or account lifecycle algorithms.
void addEnvelopeFixtureAttributes(DefaultCookieJar jar) {
  final rich = Cookie('actual-cookie-name', 'synthetic-full-attributes')
    ..domain = '.attribute.example'
    ..path = '/actual-cookie-path'
    ..secure = true
    ..httpOnly = true
    ..sameSite = SameSite.strict
    ..maxAge = 90
    ..expires = DateTime.now().toUtc().add(const Duration(days: 2));
  // Add one full-attribute root cookie so type8 reopen shows attributes lost
  // even for entries whose name/value survive the legacy root-only adapter.
  jar
    ..domainCookies['attribute-map-key.example'] = {
      '': {},
      '/different-map-path': {'alias-map-name': SerializableCookie(rich)},
    }
    ..domainCookies['bilibili.com']!['/']!['root-map-alias'] = SerializableCookie(
        Cookie('surviving-cookie-name', 'synthetic-root-attributes')
          ..domain = '.bilibili.com'
          ..path = '/'
          ..secure = true
          ..httpOnly = true
          ..sameSite = SameSite.lax
          ..maxAge = 120
          ..expires = DateTime.now().toUtc().add(const Duration(days: 2)),
    );
  // Non-const elements keep this list mutable; no const-literal lint applies.
  final keys = [
    '',
    '\u00e9',
    'e\u0301',
    '\u{1f600}',
    '\ue000',
    String.fromCharCodes(const [0xd800]),
    String.fromCharCodes(const [0xdc00]),
  ];
  for (var index = 0; index < keys.length; index++) {
    final key = keys[index];
    jar
      ..domainCookies[key] = {
        key: {
          key: SerializableCookie(
            Cookie('synthetic-utf16-entry', 'synthetic-value-$index'),
          ),
        },
      }
      ..hostCookies[key] = {};
  }
  jar.hostCookies['synthetic-empty-paths.example'] = {'': {}, '/empty': {}};
}
